/*
 * CSE 2206 - Microcontroller and Embedded System
 * Lab Assignment 3 - Part B: BME280 via I2C (HAL / STM32CubeIDE)
 * Platform : STM32F446RE Nucleo-64
 *
 * CubeIDE Configuration Summary (do in .ioc before generating code):
 *   I2C1  → Mode = I2C, PB6=SCL (AF4), PB7=SDA (AF4)
 *           Speed = Standard Mode (100 kHz)
 *   USART2 → Asynchronous, 115200, 8N1, PA2=TX, PA3=RX
 *   TIM6  → PSC=9000-1, ARR=10000-1, NVIC TIM6 enabled
 *   Clock  → SYSCLK=180 MHz via HSE PLL
 *
 * Paste this code inside the USER CODE sections of main.c.
 */

/* ---- Standard includes (already in main.c) ---- */
#include "main.h"
#include <stdio.h>
#include <string.h>

/* ---- Extern handles generated by CubeIDE ---- */
extern I2C_HandleTypeDef  hi2c1;
extern UART_HandleTypeDef huart2;
extern TIM_HandleTypeDef  htim6;

/* ------------------------------------------------------------------ */
/*  BME280 I2C Address (HAL uses 8-bit, so left-shift by 1)           */
/* ------------------------------------------------------------------ */
#define BME280_ADDR  (0x76 << 1)   /* = 0xEC */

/* ------------------------------------------------------------------ */
/*  BME280 Register Map                                                */
/* ------------------------------------------------------------------ */
#define BME280_REG_CHIP_ID    0xD0
#define BME280_REG_RESET      0xE0
#define BME280_REG_CTRL_HUM   0xF2
#define BME280_REG_CTRL_MEAS  0xF4
#define BME280_REG_CONFIG     0xF5
#define BME280_REG_PRESS_MSB  0xF7

/* ------------------------------------------------------------------ */
/*  Calibration Storage                                                */
/* ------------------------------------------------------------------ */
static uint16_t dig_T1;
static int16_t  dig_T2, dig_T3;
static uint16_t dig_P1;
static int16_t  dig_P2, dig_P3, dig_P4, dig_P5;
static int16_t  dig_P6, dig_P7, dig_P8, dig_P9;
static uint8_t  dig_H1;
static int16_t  dig_H2;
static uint8_t  dig_H3;
static int16_t  dig_H4, dig_H5;
static int8_t   dig_H6;

static int32_t  t_fine;
static float    temp_C, temp_F, pres_hPa, hum_RH;

/* ==================================================================
   B5.2 — HAL I2C Wrapper Functions
   ================================================================== */

/* Write single register */
static void BME280_HAL_I2C_WriteReg(uint8_t reg, uint8_t data)
{
    uint8_t buf[2] = { reg, data };
    HAL_I2C_Master_Transmit(&hi2c1, BME280_ADDR, buf, 2, HAL_MAX_DELAY);
}

/* Burst read using Transmit + Receive */
static void BME280_HAL_I2C_ReadRegs(uint8_t reg, uint8_t *buf, uint8_t len)
{
    HAL_I2C_Master_Transmit(&hi2c1, BME280_ADDR, &reg, 1, HAL_MAX_DELAY);
    HAL_I2C_Master_Receive (&hi2c1, BME280_ADDR, buf, len, HAL_MAX_DELAY);
}

/* Cleaner alternative using Mem API */
static void BME280_HAL_I2C_MemRead(uint8_t reg, uint8_t *buf, uint8_t len)
{
    HAL_I2C_Mem_Read(&hi2c1, BME280_ADDR, reg,
                     I2C_MEMADD_SIZE_8BIT, buf, len, HAL_MAX_DELAY);
}

/* ==================================================================
   Calibration Read
   ================================================================== */
static void BME280_HAL_ReadCalibration(void)
{
    uint8_t buf[26];

    BME280_HAL_I2C_MemRead(0x88, buf, 24);
    dig_T1 = (uint16_t)(buf[1]  << 8) | buf[0];
    dig_T2 = (int16_t) (buf[3]  << 8) | buf[2];
    dig_T3 = (int16_t) (buf[5]  << 8) | buf[4];
    dig_P1 = (uint16_t)(buf[7]  << 8) | buf[6];
    dig_P2 = (int16_t) (buf[9]  << 8) | buf[8];
    dig_P3 = (int16_t) (buf[11] << 8) | buf[10];
    dig_P4 = (int16_t) (buf[13] << 8) | buf[12];
    dig_P5 = (int16_t) (buf[15] << 8) | buf[14];
    dig_P6 = (int16_t) (buf[17] << 8) | buf[16];
    dig_P7 = (int16_t) (buf[19] << 8) | buf[18];
    dig_P8 = (int16_t) (buf[21] << 8) | buf[20];
    dig_P9 = (int16_t) (buf[23] << 8) | buf[22];

    BME280_HAL_I2C_MemRead(0xA1, buf, 1);
    dig_H1 = buf[0];

    BME280_HAL_I2C_MemRead(0xE1, buf, 7);
    dig_H2 = (int16_t)(buf[1] << 8) | buf[0];
    dig_H3 = buf[2];
    dig_H4 = (int16_t)(buf[3] << 4) | (buf[4] & 0x0F);
    dig_H5 = (int16_t)(buf[5] << 4) | (buf[4] >> 4);
    dig_H6 = (int8_t) buf[6];
}

/* ==================================================================
   BME280 Init (HAL)
   ================================================================== */
static void BME280_HAL_Init(void)
{
    uint8_t id, reg, data;

    /* Soft reset */
    reg = BME280_REG_RESET; data = 0xB6;
    HAL_I2C_Master_Transmit(&hi2c1, BME280_ADDR, (uint8_t[]){reg, data}, 2, HAL_MAX_DELAY);
    HAL_Delay(10);

    /* Chip ID */
    BME280_HAL_I2C_MemRead(BME280_REG_CHIP_ID, &id, 1);
    {
        char s[64];
        sprintf(s, "[B1] ChipID=0x%02X (expect 0x60)\r\n", id);
        HAL_UART_Transmit(&huart2, (uint8_t *)s, strlen(s), HAL_MAX_DELAY);
    }

    /* ACK check (B2) */
    if (HAL_I2C_IsDeviceReady(&hi2c1, BME280_ADDR, 3, 100) == HAL_OK)
        HAL_UART_Transmit(&huart2, (uint8_t *)"[B2] I2C ACK OK\r\n", 17, HAL_MAX_DELAY);
    else
        HAL_UART_Transmit(&huart2, (uint8_t *)"[B2] I2C ACK FAIL\r\n", 19, HAL_MAX_DELAY);

    BME280_HAL_ReadCalibration();

    BME280_HAL_I2C_WriteReg(BME280_REG_CTRL_HUM,  0x01);
    BME280_HAL_I2C_WriteReg(BME280_REG_CTRL_MEAS, 0x57);
    BME280_HAL_I2C_WriteReg(BME280_REG_CONFIG,    0x10);

    HAL_Delay(100);
}

/* ==================================================================
   Compensation Formulas (same as bare-metal)
   ================================================================== */
static int32_t BME280_CompensateTemp(int32_t adc_T)
{
    int32_t var1, var2;
    var1 = ((((adc_T >> 3) - ((int32_t)dig_T1 << 1)))
            * ((int32_t)dig_T2)) >> 11;
    var2 = (((((adc_T >> 4) - ((int32_t)dig_T1))
            * ((adc_T >> 4) - ((int32_t)dig_T1))) >> 12)
            * ((int32_t)dig_T3)) >> 14;
    t_fine = var1 + var2;
    return (t_fine * 5 + 128) >> 8;
}

static uint32_t BME280_CompensatePressure(int32_t adc_P)
{
    int64_t var1, var2, p;
    var1 = ((int64_t)t_fine) - 128000;
    var2 = var1 * var1 * (int64_t)dig_P6;
    var2 = var2 + ((var1 * (int64_t)dig_P5) << 17);
    var2 = var2 + (((int64_t)dig_P4) << 35);
    var1 = ((var1 * var1 * (int64_t)dig_P3) >> 8)
         + ((var1 * (int64_t)dig_P2) << 12);
    var1 = (((((int64_t)1) << 47) + var1) * (int64_t)dig_P1) >> 33;
    if (var1 == 0) return 0;
    p  = 1048576 - adc_P;
    p  = (((p << 31) - var2) * 3125) / var1;
    var1 = (((int64_t)dig_P9) * (p >> 13) * (p >> 13)) >> 25;
    var2 = (((int64_t)dig_P8) * p) >> 19;
    p = ((p + var1 + var2) >> 8) + (((int64_t)dig_P7) << 4);
    return (uint32_t)p;
}

static uint32_t BME280_CompensateHumidity(int32_t adc_H)
{
    int32_t v;
    v = t_fine - 76800;
    v = (((((adc_H << 14) - ((int32_t)dig_H4 << 20)
          - ((int32_t)dig_H5 * v)) + 16384) >> 15)
       * (((((((v * (int32_t)dig_H6) >> 10)
             * (((v * (int32_t)dig_H3) >> 11) + 32768)) >> 10)
            + 2097152) * (int32_t)dig_H2 + 8192) >> 14));
    v = v - (((((v >> 15) * (v >> 15)) >> 7) * (int32_t)dig_H1) >> 4);
    if (v < 0) v = 0;
    if (v > 419430400) v = 419430400;
    return (uint32_t)(v >> 12);
}

/* ==================================================================
   Read All Sensor Data
   ================================================================== */
static void BME280_ReadAll_I2C_HAL(void)
{
    uint8_t raw[8];
    BME280_HAL_I2C_MemRead(BME280_REG_PRESS_MSB, raw, 8);

    int32_t adc_P = ((int32_t)raw[0] << 12) | ((int32_t)raw[1] << 4) | (raw[2] >> 4);
    int32_t adc_T = ((int32_t)raw[3] << 12) | ((int32_t)raw[4] << 4) | (raw[5] >> 4);
    int32_t adc_H = ((int32_t)raw[6] << 8)  |  raw[7];

    int32_t  comp_T = BME280_CompensateTemp(adc_T);
    uint32_t comp_P = BME280_CompensatePressure(adc_P);
    uint32_t comp_H = BME280_CompensateHumidity(adc_H);

    temp_C   = comp_T / 100.0f;
    temp_F   = temp_C * 9.0f / 5.0f + 32.0f;
    pres_hPa = (comp_P / 256.0f) / 100.0f;
    hum_RH   = comp_H / 1024.0f;
}

/* ==================================================================
   B5.3 — HAL TIM6 Period-Elapsed Callback
   ================================================================== */
static volatile uint32_t ticks_hal = 0;

void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
    if (htim->Instance == TIM6) {
        ticks_hal++;

        /* Test B3 heartbeat */
        {
            char s[32];
            sprintf(s, "[B3] Tick:%lu\r\n", ticks_hal);
            HAL_UART_Transmit(&huart2, (uint8_t *)s, strlen(s), HAL_MAX_DELAY);
        }

        BME280_ReadAll_I2C_HAL();

        /* Test B4 plausibility */
        if (temp_C < 15.0f || temp_C > 40.0f
         || pres_hPa < 900 || pres_hPa > 1100
         || hum_RH < 0 || hum_RH > 100)
            HAL_UART_Transmit(&huart2, (uint8_t *)"[B4] Plausibility FAIL\r\n", 24, HAL_MAX_DELAY);
        else
            HAL_UART_Transmit(&huart2, (uint8_t *)"[B4] Plausibility PASS\r\n", 24, HAL_MAX_DELAY);

        /* Main sensor output */
        char msg[128];
        sprintf(msg,
            "[I2C-HAL] Temp:%.2fC Pres:%.2fhPa Hum:%.2f%%\r\n",
            temp_C, pres_hPa, hum_RH);
        HAL_UART_Transmit(&huart2, (uint8_t *)msg, strlen(msg), HAL_MAX_DELAY);
    }
}

/* ==================================================================
   main() — USER CODE sections to paste into generated main.c
   ================================================================== */
/*
   In USER CODE BEGIN 2:

    // Test UART alive
    HAL_UART_Transmit(&huart2, (uint8_t *)"[B2-UART] UART OK\r\n", 19, HAL_MAX_DELAY);

    // Banner
    const char *banner =
        "========================================\r\n"
        "BME280 via I2C -- CSE 2206 Lab B (HAL)\r\n"
        "========================================\r\n";
    HAL_UART_Transmit(&huart2, (uint8_t *)banner, strlen(banner), HAL_MAX_DELAY);

    BME280_HAL_Init();

    // Start TIM6 in interrupt mode
    HAL_TIM_Base_Start_IT(&htim6);

   // USER CODE BEGIN WHILE: nothing needed — ISR handles everything
*/